# Generated by Django 4.2.15 on 2024-08-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='post',
            name='message',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.TextField(default=True),
        ),
    ]
