# Generated by Django 4.2.15 on 2024-08-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_author_post_name_remove_post_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Contact',
        ),
    ]
