# Generated by Django 4.2.15 on 2024-08-22 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_post_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_date'], 'verbose_name': 'CONTACT FORM', 'verbose_name_plural': 'CONTACT FORMS'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
